version: 2.1

jobs:
  setup_ism: # The first job
    docker:
      - image: chrisbra/ibi:ism_project_v2
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run:
            name: Debugging information
            command: |
              whoami
              pwd
              ps -ef
              pwd
              git ls-files
        - run:
            name: Start iSM and deploy
            command: |
              bash .circleci/setup.sh &&
              echo "sleep 5 minutes" && 
              sleep 300 &
        - run:
            name: Run Tests
            command: |
              bash .circleci/test.sh

workflows:
  version: 2
  workflow_one: # name of the workflow
    jobs: # list the jobs to be running
      - setup_ism
