version: 2.1

jobs:
  build: # The first job
    docker:
      - image: chrisbra/ibi:ism_project_v2
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run: bash -c "cd ~/iway8 && ./iway8.sh base &"
        - run: echo "Hello World"
        - run: whoami
        - run: ls /
        - run: ls /home/*/
        - run: hostname
workflows:
  version: 2
  workflow_one: # name of the workflow
    jobs: # list the jobs to be running
      - build
