version: 2.1

jobs:
  setup_ism: # The first job
    docker:
      - image: chrisbra/ibi:ism_project_v2
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run:
            name: Debugging information
            command: |
              whoami
              pwd
              ps -ef
              pwd
              git ls-files
        - run:
            name: Start iSM and deploy
            command: |
              pushd ~/iway8 &&
              sed -i.bak -e '/^ *su/{s/^[^"]*"//;s/"$//}' bin/startservice.sh &&
              bin/startservice.sh base &&
              popd &&
              sleep 20 &&
              curl -L --user "${IWAY_USER}:${IWAY_PASS}" http://localhost:9999/ism >/dev/null &&
              project=$(basename $(git rev-parse --show-toplevel)) &&
              dir="/home/ibuser/iwaySDK/8.0.4/build2/projects/" &&
              mkdir -p "${dir}${project}" &&
              git archive master |  ( cd "${dir}${project}"; tar -x ) &&
              echo "ls ism_ci project" &&
              ls "${dir}${project}" &&
              pushd "${dir}/../configurations" &&
              git clone --quiet --depth=1 https://github.com/chrisbra/ci_configuration ismci &&
              echo "ls ismci configuration" &&
              ls ./ismci/ &&
              popd &&
              pushd "${dir}/.." &&
              sh build.sh BUILDAPP ismci &&
              echo "DONE"

workflows:
  version: 2
  workflow_one: # name of the workflow
    jobs: # list the jobs to be running
      - setup_ism
