version: 2.1

jobs:
  setup_ism: # The first job
    docker:
      - image: chrisbra/ibi:ism_project_v2
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run:
            name: Debugging information
            command: |
              whoami
              pwd
              ps -ef
              pwd
              git ls-files
        - run:
            name: Startup iSM
            command: |
              bash -c 'cd ~/iway8 && ./iway8.sh base'
            background: true
        - run:
            name: Start iSM and deploy
            command: |
              bash .circleci/setup.sh
        - run:
            name: Run Tests
            command: |
              bash .circleci/test.sh
        - store_test_results:
            path: /home/ibuser/test-results

workflows:
  version: 2
  workflow_one: # name of the workflow
    jobs: # list the jobs to be running
      - setup_ism
