version: 2.1

jobs:
  setup_ism: # The first job
    docker:
      - image: chrisbra/ibi:ism_project_v2
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - run: bash -c "cd ~/iway8 && ( ./iway8.sh base & ); sleep 25"

  test: # Run iSM Test Suite
    docker:
      - image: chrisbra/ibi:ism_project_v2
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run: echo "Hello World"
        - run: whoami
        - run: ls /
        - run: ls /home/*/
        - run: hostname
        - run: ps -ef

workflows:
  version: 2
  workflow_one: # name of the workflow
    jobs: # list the jobs to be running
      - setup_ism
      - test:
          requires:
            - setup_ism
