version: 2.1
orbs:
    slack: circleci/slack@4.2.0

jobs:
  test_ism: # The first job
    docker:
      - image: chrisbra/ibi:ism_project_v3
        auth:
            username: chrisbra
            password: $DOCKERHUB_PASSWORD
    steps:
        - checkout
        - run:
            name: Debugging information
            command: |
              whoami
              pwd
              ps -ef
              pwd
              git ls-files
        - run:
            name: Startup iSM
            command: |
              bash -c 'cd ~/iway8 && ./iway8.sh base'
            background: true
        - run:
            name: Prepare for Tests and Deploy
            command: |
              bash .circleci/setup.sh
        - run:
            name: Run Tests
            command: |
              bash .circleci/runtests.sh
        - slack/notify:
            channel: ismci
            event: fail
            template: basic_fail_1
        - store_test_results:
            path: /home/ibuser/test-results
        - store_artifacts:
            path: /home/ibuser/artifacts

workflows:
  version: 2
  workflow_one: # name of the workflow
    jobs: # list the jobs to be running
      - test_ism
